### ISSUE TITLE
Predicts u,v,p using single GCA-ROM

### ISSUE THREAD

**Issue by sunwoong-yang** [fpichi/gca-rom#3]
Thank you for the precious code, which is very helpful to me.

In the paper in JCP, you wrote as below:

_Given the nature of the model, with velocity and the pressure fields as unknowns, we show the adaptability of the architecture to vector problems. Thus, we consider a monolithic approach, where the three fields are concatenated as features for each node, rather than a partitioned one, where we recover independently each field._

As I understood, the GCA-ROM in your paper predicted the u,v,p at the same time with the single GCA-ROM model.
However, in the NS codes in the tutorial folder, we have to train each GCA-ROM to predict u,v,p, respectively.

1) Could you please share the original code that predicts u,v,p all at once with the single GCA-ROM?

Also, additional question.

2) The current GCA-ROM framework seems to be only trained and tested on the same number of nodes (N_h in the paper), due to its conv nature. Do you have any plan to extend this framework so that it can be applied to various graphs with different numbers of nodes?

**Comment by fpichi** [comment]
Dear Sunwoong, thanks a lot for your interest in our research!
You're right the online version of the code, at the moment, only takes care of the reconstruction of scalar fields.
The main reason behind this choice was the excessive size of the dataset for the "monolithic" approach (u,v,p predicted with the same architecture). 

Despite this, the main changes needed to deal with a vector problem are minimal, namely:

1. in network.py, line 53, change the dimensionality  of hidden_channels to n (=3 for Navier-Stokes with u,v,p)
```python
self.hidden_channels = [n]*self.in_channels
``` 

2. in loader.py, line 34, import all components separately
```python
self.VX = torch.tensor(self.data_mat[VX])
self.VY = torch.tensor(self.data_mat[VY])
self.P = torch.tensor(self.data_mat[P])
``` 

3. in preprocessing.py, line 38, stacking the components together in var
```python
var = torch.stack((dataset.VX, dataset.VY,, dataset.P), dim=2)
``` 

I'm planning to push a new version with the aforementioned changes and a simpler vector problem based on Navier-Stokes soon.

Regarding your question: Indeed a current limitation of this approach is the node's cardinality due to the feedforward layers. We have already developed and currently testing a related architecture specifically suited to deal with multi-fidelity scenarios both in the training and testing phases.

**Comment by sunwoong-yang** [comment]
Thank you for getting back to me so quickly!

1. Can I understand the word "cardinality" as the current version of the code cannot use the different number of nodes, that is, the same size of the mesh should be used for all training data, and all test data??

2. Also, in this context, does the multi-fidelity scenarios mean the different resolution grids can be used during the training/test?
3. Then, could you please tell me when the upcoming code version will be released?

I am really looking forward to seeing your extension :)

**Comment by fpichi** [comment]
1-1. Here with "cardinality" I meant exactly the number of nodes, which, in the current version, has to be the same for all the training and testing samples (here we want to generalize over the parameter space and not in the physical domain).
1-2. The MLP is the feedforward layer I was referring to, and it is indeed the reason why I cannot consider different fidelities. Notice that if one considers only a GCN architecture without MLP/bottleneck, then there is no issue but the architecture has to be modified to recover the parameter-to-latent space map.

2-1. Exactly, in the new architecture one will be able to mix fidelities during both training and testing phases, learning from different grids, performing super-resolution, and generalizing over the physical domain.
2-2. We still want to perform further tests to be sure to highlight all the potentialities, but we are close to reaching a final version of the code/manuscript, probably 1/2 months will be enough.

Thanks again!

**Comment by sunwoong-yang** [comment]
Thank you very much for your kind reply.

Looking forward to the next version of the code/manuscript and good luck!
